[package]
name = "test-harness"
version = "0.1.0"
edition = "2021"
rust-version = "1.88.0"

[dependencies]
dioxus = { workspace = true, features = ["launch", "lib", "router"] }
dioxus-components = { path = "../dioxus-components" }
dioxus-router = "0.7.9"
dioxus-icons = "0.1.0"
dioxus-primitives.workspace = true
dioxus-i18n = { git = "https://github.com/ealmloff/dioxus-i18n", branch = "bump-dioxus" }
manganis = "0.7.9"
palette = "0.7.6"
strum = { version = "0.27.2", features = ["derive"] }
tracing = { workspace = true }
time = { version = "0.3.44", features = ["std", "macros"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
web-sys = { version = "0.3.82", features = ["Location", "Window"] }

[features]
default = ["web"]
web = ["dioxus/web", "dioxus-primitives/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
