name: Playwright Tests

on:
  push:
    branches:
      - main
    paths:
      - /**
      - playwright/**
      - preview/**/*.css
      - preview/**/*.rs
      - preview/**/Cargo.toml
      - primitives/**/*.rs
      - primitives/**/Cargo.toml
      - .github/**
      - Cargo.toml

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - /**
      - playwright/**
      - preview/**/*.css
      - preview/**/*.rs
      - preview/**/Cargo.toml
      - primitives/**/*.rs
      - primitives/**/Cargo.toml
      - .github/**
      - Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    if: github.event.pull_request.draft == false
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      # Do our best to cache the toolchain and node install steps
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: DioxusLabs/dioxus-ci/actions/setup-dioxus@v0.1.0
        with:
          toolchain: 1.88.0
          targets: x86_64-unknown-linux-gnu,wasm32-unknown-unknown
          cache-on-failure: "true"
      - uses: DioxusLabs/dioxus-ci/actions/install-dioxus-cli@v0.1.0
        with:
          version: 0.7.9
      - name: Install dependencies
        run: cd ./playwright && npm ci
      - name: Install Playwright Browsers
        run: cd ./playwright && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd ./playwright && npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
